import { useEffect, useState, type ReactNode } from 'react';
import * as Tabs from '@radix-ui/react-tabs';
import { useQuery } from '@tanstack/react-query';
import { ArrowLeft, ArrowRight, Check, ChevronRight, CircleHelp, FileCheck2, FileText, FolderOpen, GitCompareArrows, History, Layers3, LogIn, LogOut, MessageSquareText, Plus, ShieldCheck, Users, WandSparkles } from 'lucide-react';
import { api, ApiError, demoOnly, getAuth, navigate, queryClient, write } from './api';
import { Badge, Button, ErrorBox, LanguageContext, Loading, Modal, SectionHeading, statusLabel, useLang } from './ui';
import { RequirementsForm, RequirementStrip } from './RequirementsForm';
import { Comparison } from './Comparison';
import { Questions } from './Questions';
import { Documents } from './Documents';
import { EvidencePanel } from './EvidencePanel';
import { DecisionPanel, HistoryPanel, MembersPanel, Review } from './WorkspacePanels';
import type { Auth, CaseDetail, CaseSummary, Fact, Lang, MutateCase } from './types';

export default function App(){
  const [lang,setLang]=useState<Lang>(()=>localStorage.getItem('kontroferta-language')==='en'?'en':'pl');const [route,setRoute]=useState(window.location.hash.slice(1)||'/demo');
  const auth=useQuery({queryKey:['auth'],queryFn:getAuth,retry:false});
  useEffect(()=>{const change=()=>setRoute(window.location.hash.slice(1)||'/demo');window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change);},[]);
  useEffect(()=>{document.documentElement.lang=lang;localStorage.setItem('kontroferta-language',lang);},[lang]);
  const t=(pl:string,en:string)=>lang==='pl'?pl:en;
  let page:ReactNode;
  if(demoOnly)page=<Workspace key="demo" id="demo" publicDemo auth={auth.data}/>;
  else if(route.startsWith('/invite/'))page=<Invitation token={route.slice(8)} auth={auth.data}/>;
  else if(route==='/cases')page=<Cases auth={auth.data}/>;
  else if(route.startsWith('/cases/'))page=<Workspace key={route} id={route.slice(7)} publicDemo={false} auth={auth.data}/>;
  else page=<Workspace key="demo" id="demo" publicDemo auth={auth.data}/>;
  return <LanguageContext.Provider value={{lang,t}}><a className="skip-link" href="#main" onClick={event=>{event.preventDefault();const main=document.getElementById('main');main?.focus();main?.scrollIntoView();}}>{t('Przejdź do treści','Skip to content')}</a><header className="app-header"><a className="brand" href="#/demo" aria-label="KontrOferta"><span className="brand-icon"><GitCompareArrows size={24}/></span><span>Kontr<span>Oferta</span></span></a><nav className="header-nav" aria-label={t('Główna nawigacja','Main navigation')}>{!demoOnly?<a href="#/cases" className={route.startsWith('/cases')?'active':''}><FolderOpen size={17}/>{t('Moje sprawy','My cases')}</a>:null}<a href="#/demo" className={route==='/demo'?'active':''}><Layers3 size={17}/>{t('Zobacz przykład','View example')}</a></nav><div className="header-actions"><button className="language-switch" onClick={()=>setLang(prev=>prev==='pl'?'en':'pl')} aria-label={t('Switch language to English','Zmień język na polski')}>{lang==='pl'?'EN':'PL'}</button>{demoOnly?<Badge tone="blue">{t('Zapisany przykład','Recorded example')}</Badge>:auth.data?.user?<><span className="user-name">{auth.data.user.name}</span><Button variant="ghost" title={t('Wyloguj','Sign out')} onClick={async()=>{await write('/auth/logout');queryClient.clear();await getAuth();window.location.hash='/demo';window.location.reload();}}><LogOut size={17}/><span className="desktop-label">{t('Wyloguj','Sign out')}</span></Button></>:auth.data?.guestEnabled?<GuestEntry/>:<a className="button button-secondary login-button" href={`/api/auth/login?next=${encodeURIComponent('/#'+(window.location.hash.slice(1)||'/cases'))}`}><LogIn size={16}/>{t('Zaloguj się','Sign in')}</a>}</div></header><main id="main" className="app-main" tabIndex={-1}>{auth.error?<ErrorBox error={auth.error} retry={()=>auth.refetch()}/>:null}{page}</main><footer className="app-footer"><span>KontrOferta <span className="footer-dot">·</span> {t('Porównanie ofert obsługi technicznej','Technical service offer comparison')}</span><a href="/materials/">{t('Film, prezentacja i instrukcja','Video, slides and guide')}</a></footer></LanguageContext.Provider>;
}
function Cases({auth}: {auth?:Auth}){
  const {t}=useLang();const [create,setCreate]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState<unknown>(null);
  const cases=useQuery({queryKey:['cases'],queryFn:()=>api<{cases:CaseSummary[]}>('/cases'),enabled:Boolean(auth?.user)});
  if(!auth?.user)return <SignInPrompt auth={auth}/>;
  const start=async()=>{if(!auth.guestEnabled){setCreate(true);return;}setBusy(true);setError(null);try{const c=await write<CaseDetail>('/cases/demo-fresh');await queryClient.invalidateQueries({queryKey:['cases']});navigate(`/cases/${c.id}`);}catch(e){setError(e);}finally{setBusy(false);}};
  return <div className="cases-page"><SectionHeading eyebrow={t('TWÓJ OBSZAR PRACY','YOUR WORKSPACE')} title={t('Sprawy, do których możesz wrócić','Decisions you can come back to')} action={<Button busy={busy} onClick={start}><Plus size={18}/>{auth.guestEnabled?t('Nowa sprawa z dokumentami demo','New case with demo documents'):t('Nowa sprawa','New case')}</Button>}>{t('Dokumenty, pytania i uzgodnienia w jednym miejscu. Każdy wybór z własną historią.','Documents, questions and findings in one place. Every choice with its own history.')}</SectionHeading>{cases.isPending?<Loading/>:cases.error?<ErrorBox error={cases.error}/>:null}
    <div className="cases-grid">{cases.data?.cases.map(item=><a className="card case-card" key={item.id} href={`#/cases/${item.id}`}><div className="inline spread"><div className="case-icon"><FolderOpen size={24}/></div><Badge tone={item.status==='needs_clarification'?'warn':item.status==='unique_winner'?'good':'neutral'}>{statusLabel(item.status,t)}</Badge></div><h3>{item.title}</h3><p>{t('Wersja','Version')} {item.revision} · {statusLabel(item.role,t)}</p><div className="inline spread small muted"><span>{new Date(item.updatedAt).toLocaleDateString()}</span><ArrowRight size={18}/></div></a>)}<button className="case-card new-case-card" disabled={busy} onClick={start}><span className="case-icon"><Plus size={26}/></span><h3>{auth.guestEnabled?t('Zaimportuj oferty demonstracyjne','Import demonstration offers'):t('Zacznij nowe porównanie','Start a new comparison')}</h3><p>{auth.guestEnabled?t('Własna sprawa z czterema syntetycznymi PDF, gotowa do nowej analizy.','Your own case with four synthetic PDFs, ready for new analysis.'):t('Określ wymagania i dodaj oferty.','Set requirements and add offers.')}</p></button></div>
    <section className="example-banner"><div><p className="eyebrow">{t('POZNAJ CAŁY PRZEPŁYW','EXPLORE THE WHOLE FLOW')}</p><h2>{t('Czy dopłata za technika zmieni Twój wybór?','Will the technician surcharge change your choice?')}</h2><p>{auth.guestEnabled?t('Zaimportuj cztery syntetyczne pliki PDF do własnej sprawy. Analizę przez Gemini uruchomisz osobno po sprawdzeniu dokumentów.','Import four synthetic PDF files into your own case. You will run Gemini analysis separately after reviewing the documents.'):t('Fikcyjne wydarzenie AV. Zobacz, dlaczego pytanie o technika może zmienić wybór.','A fictional AV event. See why asking about the technician can change your choice.')}</p></div><Button variant="secondary" busy={busy} onClick={async()=>{setBusy(true);setError(null);try{const c=await write<CaseDetail>(auth.guestEnabled?'/cases/demo-fresh':'/cases/demo');queryClient.invalidateQueries({queryKey:['cases']});navigate(`/cases/${c.id}`);}catch(e){setError(e);}finally{setBusy(false);}}}><WandSparkles size={17}/>{auth.guestEnabled?t('Importuj dokumenty demonstracyjne','Import demonstration documents'):t('Utwórz własną kopię przykładu','Create your own example copy')}</Button></section>{error?<ErrorBox error={error}/>:null}
    <Modal open={create} onOpenChange={setCreate} title={t('Nowa sprawa','New case')} description={t('Najpierw nazwij wydarzenie i określ porównywalny zakres.','First name the event and define a comparable scope.')} wide><RequirementsForm onSave={async(title,requirements)=>{const data=await write<CaseDetail>('/cases',{title,requirements,expectedRevision:0});queryClient.setQueryData(['case',data.id],data);await queryClient.invalidateQueries({queryKey:['cases']});setCreate(false);navigate(`/cases/${data.id}`);}}/></Modal>
  </div>;
}
function SignInPrompt({auth}: {auth?:Auth}){const {t}=useLang();if(auth?.guestEnabled)return <section className="sign-in-card card"><div className="case-icon"><ShieldCheck size={32}/></div><p className="eyebrow">{t('INTERAKTYWNE DEMO','INTERACTIVE DEMO')}</p><h1>{t('Porównaj pełny koszt ofert na wydarzenie','Compare full offer costs for your event')}</h1><p>{t('AI odczytuje oferty i aneksy, a aplikacja porównuje pełny koszt z wymaganiami wydarzenia. Sprawdzisz, która odpowiedź wykonawcy zmienia wybór.','AI reads offers and addenda, then the app compares full costs against your event requirements. See which supplier answer changes your choice.')}</p><p className="small muted">{t('Demo zawiera fikcyjne oferty. Twoja sesja w tej przeglądarce ma oddzielne sprawy. Korzystaj wyłącznie z danych syntetycznych, bez danych osobowych.','The demo uses fictional offers. Your browser session has separate cases. Use synthetic documents only, without personal data.')}</p><GuestEntry/><a className="text-link" href="#/demo">{t('Zobacz zapisany przykład','View the recorded example')}</a></section>;return <section className="sign-in-card card"><div className="case-icon"><ShieldCheck size={32}/></div><p className="eyebrow">{t('PRYWATNE DOKUMENTY I DECYZJE','PRIVATE DOCUMENTS AND DECISIONS')}</p><h1>{t('Zaloguj się, aby pracować na własnych ofertach.','Sign in to work with your own offers.')}</h1><p>{t('Wróć do zapisanych spraw na innym urządzeniu. Udostępniaj dostęp wybranym osobom i zatwierdzaj konkretne wersje.','Return to saved cases on another device. Share access with selected people and approve specific versions.')}</p><a className="button button-primary" href={`/api/auth/login?next=${encodeURIComponent('/#'+(window.location.hash.slice(1)||'/cases'))}`}><LogIn size={18}/>{t('Zaloguj się bezpiecznie','Sign in securely')}</a><a className="text-link" href="#/demo">{t('Najpierw obejrzyj fikcyjny przykład','Explore the fictional example first')}<ArrowRight size={17}/></a></section>;}
function Workspace({id,publicDemo,auth}: {id:string;publicDemo:boolean;auth?:Auth}){
  const {t}=useLang();const [tab,setTab]=useState('compare');const [factId,setFactId]=useState<string|null>(null);const [requirementsOpen,setRequirementsOpen]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState<unknown>(null);const [conflict,setConflict]=useState<ApiError|null>(null);
  const result=useQuery({queryKey:['case',id],queryFn:()=>api<CaseDetail>(publicDemo?'/demo':`/cases/${id}`),enabled:publicDemo||Boolean(auth?.user),refetchInterval:query=>query.state.data?.jobs?.some(j=>['running','queued'].includes(j.status))?3000:false});
  const data=result.data;const jobId=data?.jobs?.find(j=>['running','queued'].includes(j.status))?.id;
  useEffect(()=>{if(!jobId||publicDemo)return;const events=new EventSource(`/api/jobs/${jobId}/events`,{withCredentials:true});const refresh=()=>{void queryClient.invalidateQueries({queryKey:['case',id]});};events.onmessage=refresh;events.addEventListener('progress',refresh);events.addEventListener('job',refresh);events.onerror=()=>{void queryClient.invalidateQueries({queryKey:['case',id]});};return()=>events.close();},[id,jobId,publicDemo]);
  const mutate:MutateCase=async(path,body={},method='POST')=>{if(!data)throw new Error('Case not loaded');let payload:Record<string,unknown>|FormData;if(body instanceof FormData){body.set('expectedRevision',String(data.revision));payload=body;}else payload={...body,expectedRevision:data.revision};try{const updated=await write<CaseDetail|{case:CaseDetail}>(path.startsWith('/jobs/')?path:`/cases/${id}${path}`,payload,method);if(updated&&typeof updated==='object'){if('revision' in updated)queryClient.setQueryData(['case',id],updated);else if('case' in updated)queryClient.setQueryData(['case',id],updated.case);}await queryClient.invalidateQueries({queryKey:['cases']});return updated;}catch(e){if(e instanceof ApiError&&e.status===409){setConflict(e);}throw e;}};
  if(!publicDemo&&!auth?.user)return <SignInPrompt auth={auth}/>;
  if(result.isPending)return <Loading/>;
  if(result.error)return <ErrorBox error={result.error} retry={()=>result.refetch()}/>;
  if(!data)return null;
  const readOnly=publicDemo||data.role==='observer';const critical=data.facts.filter(f=>f.critical!==false&&!data.offers.some(o=>o.excluded_reason&&o.id===(f.offer_id||f.offerId))&&f.confirmation!=='confirmed').length;const tabItems=[['compare',t('Porównanie','Comparison'),GitCompareArrows],['questions',t('Pytania','Questions'),MessageSquareText],['documents',t('Dokumenty','Documents'),FileText],['review',t('Przegląd','Review'),FileSearchIcon],['decision',t('Decyzja i raport','Decision & report'),FileCheck2],['history',t('Historia','History'),History],['members',t('Dostęp','Access'),Users]] as const;
  return <div className="workspace"><div className="breadcrumbs"><a href={demoOnly?'#/demo':'#/cases'}>{demoOnly?t('KontrOferta','KontrOferta'):t('Moje sprawy','My cases')}</a><ChevronRight size={14}/><span>{publicDemo?t('Przykład AV','AV example'):data.title}</span></div>
    {publicDemo?<div className="demo-banner"><span><span className="demo-dot"/>{t('Zapisany przykład','Recorded example')} <span className="demo-separator">·</span> {t('Wyłącznie fikcyjne dokumenty. To nie jest nowa analiza AI.','Fictional documents only. This is not a new AI analysis.')}</span>{demoOnly?<Badge>{t('Odczyt i symulacja założeń','Read and explore assumptions')}</Badge>:auth?.user?<Button variant="ghost" busy={busy} onClick={async()=>{setBusy(true);setError(null);try{const copied=await write<CaseDetail>(auth.guestEnabled?'/cases/demo-fresh':'/cases/demo');navigate(`/cases/${copied.id}`);}catch(e){setError(e);}finally{setBusy(false);}}}>{auth.guestEnabled?t('Importuj do własnej sprawy','Import into your own case'):t('Pracuj na własnej kopii','Work on your own copy')}<ArrowRight size={16}/></Button>:auth?.guestEnabled?<GuestEntry/>:<a href="/api/auth/login" className="text-link">{t('Zaloguj i wypróbuj','Sign in and try')}<ArrowRight size={16}/></a>}</div>:null}
    <div className="workspace-title"><div><p className="eyebrow">{publicDemo?t('PRZYKŁAD · ORGANIZACJA WYDARZENIA','EXAMPLE · EVENT PLANNING'):t('PORÓWNANIE OFERT','OFFER COMPARISON')}</p><h1>{data.title}</h1><p>{String(data.requirements.scope||data.requirements.description||t('Pełny zakres. Sprawdzalne źródła.','Full scope. Verifiable sources.'))}</p></div><div className="version-pill"><span className="version-dot"/>{t('Wersja','Version')} {data.revision}<small>{publicDemo?t('Tylko odczyt','Read only'):statusLabel(data.role,t)}</small></div></div>
    <RequirementStrip requirements={data.requirements} readOnly={readOnly} onEdit={()=>setRequirementsOpen(true)}/>{error?<ErrorBox error={error}/>:null}
    <Tabs.Root value={tab} onValueChange={setTab} className="workspace-tabs"><Tabs.List className="tab-list" aria-label={t('Widoki sprawy','Case views')}>{tabItems.map(([value,label,Icon])=><Tabs.Trigger className="tab-trigger" value={value} key={value}><Icon size={17}/>{label}{value==='review'&&critical>0?<span className="tab-count">{critical}</span>:value==='documents'?<span className="tab-count neutral">{data.documents.length}</span>:null}</Tabs.Trigger>)}</Tabs.List><Tabs.Content value="compare"><Comparison data={data} onEvidence={f=>setFactId(f.id)} onQuestion={()=>setTab('questions')} onDocuments={()=>setTab('documents')} onReview={()=>setTab('review')}/></Tabs.Content><Tabs.Content value="questions"><Questions data={data} mutate={mutate} readOnly={readOnly} publicDemo={publicDemo} onReview={()=>setTab('review')}/></Tabs.Content><Tabs.Content value="documents"><Documents data={data} mutate={mutate} readOnly={readOnly} publicDemo={publicDemo} syntheticOnly={Boolean(auth?.guestEnabled)}/></Tabs.Content><Tabs.Content value="review"><Review data={data} mutate={mutate} readOnly={readOnly} onEvidence={f=>setFactId(f.id)}/></Tabs.Content><Tabs.Content value="decision"><DecisionPanel data={data} mutate={mutate} readOnly={readOnly} publicDemo={publicDemo} onReview={()=>setTab('review')}/></Tabs.Content><Tabs.Content value="history"><HistoryPanel data={data} mutate={mutate} readOnly={readOnly} publicDemo={publicDemo}/></Tabs.Content><Tabs.Content value="members"><MembersPanel data={data} mutate={mutate} readOnly={readOnly}/></Tabs.Content></Tabs.Root>
    <EvidencePanel fact={data.facts.find(f=>f.id===factId)||null} data={data} onClose={()=>setFactId(null)} mutate={mutate} readOnly={readOnly} publicDemo={publicDemo}/>
    <Modal open={requirementsOpen} onOpenChange={setRequirementsOpen} title={t('Wymagania wydarzenia','Event requirements')} wide>{readOnly?<div className="stack"><p>{String(data.requirements.scope||data.requirements.description||'')}</p><dl className="metadata">{Object.entries(data.requirements).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{typeof value==='object'?JSON.stringify(value):String(value)}</dd></div>)}</dl><p>{t('Reguła: minimalny pełny koszt spośród ofert spełniających wszystkie wymagania.','Rule: lowest full cost among offers satisfying all requirements.')}</p></div>:<RequirementsForm title={data.title} requirements={data.requirements} onPropose={text=>write(`/cases/${id}/requirements/propose`,{text,consent:true,expectedRevision:data.revision})} onSave={async(title,requirements)=>{await mutate('',{title,requirements},'PATCH');setRequirementsOpen(false);}}/>}</Modal>
    <Modal open={Boolean(conflict)} onOpenChange={open=>!open&&setConflict(null)} title={t('Ktoś zmienił tę sprawę','This case has changed')}><div className="notice warning"><CircleHelp size={21}/><p>{t('Twój zapis nie został wykonany. Sprawdź nowszą wersję i różnice w historii, a potem ponów zmianę.','Your change was not saved. Review the newer version and its history, then retry your change.')}</p></div><p>{t('Otwarta wersja','Opened version')}: {data.revision}. {t('Bieżąca wersja','Current version')}: {String(conflict?.detail.currentRevision||'?')}.</p><Button onClick={async()=>{await result.refetch();setTab('history');setConflict(null);}}>{t('Wczytaj i pokaż historię','Reload and view history')}<ArrowRight size={17}/></Button></Modal>
  </div>;
}
function FileSearchIcon({size=17}: {size?:number}){return <ShieldCheck size={size}/>;}
function Invitation({token,auth}: {token:string;auth?:Auth}) {const {t}=useLang();const [busy,setBusy]=useState(false);const [error,setError]=useState<unknown>(null);if(!auth?.user)return <SignInPrompt auth={auth}/>;return <section className="card sign-in-card"><Users size={35}/><h1>{t('Zaproszenie do wspólnej sprawy','Invitation to a shared case')}</h1><p>{t('Przyjęcie jednorazowego zaproszenia doda Cię do wskazanej sprawy z rolą określoną przez właściciela.','Accepting this one-time invitation adds you to the case with the role chosen by its owner.')}</p>{error?<ErrorBox error={error}/>:null}<Button busy={busy} onClick={async()=>{setBusy(true);setError(null);try{const data=await write<CaseDetail>(`/invitations/${encodeURIComponent(token)}/accept`);navigate(`/cases/${data.id}`);}catch(e){setError(e);}finally{setBusy(false);}}}><Check size={18}/>{t('Przyjmij zaproszenie','Accept invitation')}</Button></section>;}

function GuestEntry(){const {t}=useLang();const [busy,setBusy]=useState(false);const [error,setError]=useState<unknown>(null);return <div><Button busy={busy} onClick={async()=>{setBusy(true);setError(null);try{await getAuth();await write('/auth/guest');const auth=await getAuth();queryClient.setQueryData(['auth'],auth);await queryClient.invalidateQueries({queryKey:['cases']});navigate('/cases');}catch(e){setError(e);}finally{setBusy(false);}}}><LogIn size={16}/>{t('Wypróbuj w osobnej sesji','Try in your own session')}</Button>{error?<ErrorBox error={error}/>:null}</div>;}
