import { useEffect, useRef, useState } from 'react';
import { FileSearch, ExternalLink, Check, PencilLine, AlertCircle } from 'lucide-react';
import { Badge, Button, ErrorBox, Fold, Modal, factLabel, factDisplay, offerName, statusLabel, useLang } from './ui';
import { valueText } from './api';
import { documentUrl } from './Documents';
import type { CaseDetail, DocumentRecord, Evidence, Fact, MutateCase } from './types';

export function EvidencePanel({fact,data,onClose,mutate,readOnly,publicDemo}: {fact:Fact|null;data:CaseDetail;onClose:()=>void;mutate:MutateCase;readOnly:boolean;publicDemo:boolean}) {
  const {t,lang}=useLang();const [selected,setSelected]=useState(0);const [value,setValue]=useState('');const [unit,setUnit]=useState('');const [reason,setReason]=useState('');const [edit,setEdit]=useState(false);const [error,setError]=useState<unknown>(null);const [busy,setBusy]=useState(false);
  useEffect(()=>{setSelected(0);setValue(valueText(fact?.value));setUnit(fact?.unit||'');setReason('');setEdit(false);setError(null);},[fact?.id]);
  const moneyFact=Boolean(fact&&(/^(price(?:_|$)|cost$|deposit$|payment$|cancellation$)/.test(String(fact.key))||['minor','major','pln','eur','zł','zl'].includes(String(fact.unit).toLowerCase())));
  const evidences=fact?.evidence||[];const evidence=evidences[selected];const doc=data.documents.find(d=>d.id===(evidence?.source_id||evidence?.document_id||evidence?.documentId));
  async function save(confirmation:string){if(!fact)return;setBusy(true);setError(null);try{let parsed:unknown=value;if(typeof fact.value==='number'){parsed=Number(moneyFact?value.replace(',','.'):value);if(!Number.isFinite(parsed))throw new Error(t('Podaj poprawną liczbę.','Enter a valid number.'));}else if(typeof fact.value==='boolean'){if(!['true','false'].includes(value))throw new Error(t('Wpisz true lub false.','Enter true or false.'));parsed=value==='true';}else if(typeof fact.value==='object'){try{parsed=JSON.parse(value);}catch{throw new Error(t('Podaj poprawny JSON dla tego pola.','Enter valid JSON for this field.'));}}await mutate(`/facts/${fact.id}`,{value:parsed,...(moneyFact&&unit!==(fact.unit||'')&&['minor','major'].includes(unit)?{unit}:{}),reason:reason.trim()||t('Sprawdzono oryginał i zakres interpretacji.','Reviewed the original and scope of interpretation.'),confirmation},'PATCH');onClose();}catch(e){setError(e);}finally{setBusy(false);}}
  return <Modal open={Boolean(fact)} onOpenChange={open=>!open&&onClose()} title={t('Dowód i interpretacja','Evidence and interpretation')} description={t('Oryginał pozostaje niezmienny. Korekta człowieka jest nową wersją z własnym uzasadnieniem.','The original remains unchanged. A human correction is a new version with its own rationale.')} wide side>
    {fact?<div className="evidence-layout"><div className="evidence-interpretation stack"><div><p className="eyebrow">{offerName(data.offers,fact.offer_id||fact.offerId)} · {t('POLE DECYDUJĄCE','DECISION FIELD')}</p><h3>{factLabel(fact,t)}</h3></div><div className="fact-value"><span className="small muted">{t('Zapisana wartość','Saved value')}</span><strong tabIndex={0}>{factDisplay(fact,t,lang,String(data.requirements.currency||'PLN'),String(data.requirements.timezone||'Europe/Warsaw'))}</strong></div><div className="stack-sm"><Badge tone={fact.confirmation==='confirmed'?'good':'warn'}>{statusLabel(fact.confirmation||fact.status||'proposed',t)}</Badge><span className="small">{t('Pochodzenie','Origin')}: {statusLabel(String(fact.provenance||fact.origin||'document'),t)}</span><span className="small">{t('Sprawdzenie cytatu','Quote validation')}: {evidence?.quote_validated===true||evidence?.citation_valid===true||fact.citation_valid===true||evidence?.validated===true?t('Cytat odnaleziony w źródle','Quote located in the source'):t('Sprawdź oryginał i metodę odczytu','Check the original and reading method')}</span></div>
      {fact.conflict?<div className="notice warning" role="alert"><AlertCircle size={18}/><p>{String(fact.review_reason||t('Wykryto konflikt. Porównaj wartość i jednostkę z oryginałem przed potwierdzeniem.','A conflict was found. Compare the value and unit with the original before confirming.'))}</p></div>:null}
      {fact.scope?<p className="small"><b>{t('Zakres','Scope')}:</b> {valueText(fact.scope)}</p>:null}{fact.condition?<p className="small"><b>{t('Warunek','Condition')}:</b> {valueText(fact.condition)}</p>:null}
      {evidence?<><h4>{t('Fragment źródłowy','Source passage')}</h4><blockquote className="source-quote" tabIndex={0}>{evidence.quote||t('Brak zapisanego cytatu','No recorded quotation')}<footer>{doc?.filename||doc?.name||evidence.document_id} · {t('strona','page')} {evidence.page||1} · {evidence.method==='pdf_text'?t('tekst z PDF','PDF text'):/ocr|tesseract/i.test(evidence.method||'')?t('tekst rozpoznany ze skanu (OCR)','text recognised from a scan (OCR)'):t('odczyt dokumentu','document text')}</footer></blockquote></>:<div className="notice warning"><AlertCircle size={18}/><p>{t('To pole nie ma cytatu. Własne ustalenie musi mieć autora i uzasadnienie; nie staje się tekstem dokumentu.','This field has no quotation. A personal finding needs an author and rationale; it does not become document text.')}</p></div>}
      {!readOnly?<><Button variant="secondary" onClick={()=>setEdit(!edit)}><PencilLine size={16}/>{edit?t('Zwiń korektę','Collapse correction'):t('Popraw interpretację','Correct interpretation')}</Button>{edit?<>{moneyFact?<label className="field"><span>{t('Jednostka kwoty','Amount unit')}</span><select value={unit} onChange={e=>setUnit(e.target.value)}>{!['minor','major'].includes(fact.unit||'')?<option value={fact.unit||''}>{t('Zapisana jednostka','Recorded unit')}: {fact.unit||t('brak','none')}</option>:null}<option value="minor">{t(`Najmniejsza jednostka (100 = 1 ${data.requirements.currency||'PLN'})`,`Minor unit (100 = 1 ${data.requirements.currency||'PLN'})`)}</option><option value="major">{t(`Jednostka główna (${data.requirements.currency||'PLN'})`,`Major unit (${data.requirements.currency||'PLN'})`)}</option></select></label>:null}<label className="field"><span>{unit==='minor'?t(`Nowa wartość w jednostce najmniejszej (100 = 1 ${data.requirements.currency||'PLN'})`,`New value in minor units (100 = 1 ${data.requirements.currency||'PLN'})`):t('Nowa wartość (w zapisanej jednostce)','New value (in the recorded unit)')}</span><textarea value={value} onChange={e=>setValue(e.target.value)}/></label><label className="field"><span>{t('Uzasadnienie własnej korekty','Reason for your correction')}</span><textarea value={reason} onChange={e=>setReason(e.target.value)} required/></label></>:null}{error?<ErrorBox error={error}/>:null}<Button busy={busy} disabled={edit&&!reason.trim()} onClick={()=>save('confirmed')}><Check size={17}/>{edit?t('Zapisz i potwierdź korektę','Save and confirm correction'):t('Potwierdź tę interpretację','Confirm this interpretation')}</Button></>:null}
      <p className="small muted">{t('Potwierdzenie znaczenia nie gwarantuje wykonania usługi przez kontrahenta.','Confirming the interpretation does not guarantee supplier performance.')}</p>
    </div><div className="evidence-original"><div className="inline wrap spread"><h4><FileSearch size={17}/>{t('Oryginał dokumentu','Original document')}</h4>{doc?<a className="text-link" href={documentUrl(data,doc,publicDemo)} target="_blank" rel="noreferrer">{t('Pobierz','Download')}<ExternalLink size={15}/></a>:null}</div>{evidences.length>1?<label className="field"><span>{t('Dowód','Evidence')}</span><select value={selected} onChange={e=>setSelected(Number(e.target.value))}>{evidences.map((ev,i)=><option key={ev.id||i} value={i}>{i+1}. {ev.document_id||ev.documentId} · {t('strona','page')} {ev.page||1}</option>)}</select></label>:null}{doc?<DocumentPreview key={`${doc.id}-${evidence?.page}`} doc={doc} url={documentUrl(data,doc,publicDemo)} evidence={evidence}/>:<div className="empty"><FileSearch size={30}/><p>{t('Brak oryginału przypisanego do tego pola. Sprawdź pochodzenie ustalenia.','No original document is attached to this field. Review the finding’s provenance.')}</p></div>}</div></div>:null}
  </Modal>;
}
function DocumentPreview({doc,url,evidence}: {doc:DocumentRecord;url:string;evidence?:Evidence}) {
  const {t}=useLang();const isPDF=String(doc.mime||doc.mime_type||doc.mimeType||doc.filename||doc.name).match(/pdf/i);const isImage=String(doc.mime||doc.mime_type||doc.mimeType||doc.filename||doc.name).match(/image|png|jpe?g/i);
  const text=doc.pages?.find(p=>(p.page||p.number)===(evidence?.page||1))?.text||doc.pages?.[0]?.text||doc.text;
  return <div>{isPDF?<PdfPage url={url} pageNumber={evidence?.page||1} bbox={evidence?.bbox}/>:isImage?<img className="document-image" src={url} alt={t('Oryginał obrazu źródłowego','Original source image')}/>:<TextDocument url={url} text={text} quote={evidence?.quote}/>}<Fold title={t('Odczyt tekstowy strony','Text extracted from the page')}><HighlightedText text={text||evidence?.quote||t('Brak warstwy tekstowej. Sprawdź obraz strony.','No text layer available. Inspect the page image.')} quote={evidence?.quote}/></Fold></div>;
}
function TextDocument({url,text,quote}: {url:string;text?:string;quote?:string}) {const [loaded,setLoaded]=useState(text||'');const [error,setError]=useState(false);const {t}=useLang();useEffect(()=>{if(text)return;const controller=new AbortController();fetch(url,{credentials:'same-origin',signal:controller.signal}).then(r=>{if(!r.ok)throw new Error();return r.text();}).then(setLoaded).catch(e=>{if(e.name!=='AbortError')setError(true);});return()=>controller.abort();},[url,text]);return <div className="document-paper">{error?<p>{t('Nie udało się pobrać oryginału.','The original could not be retrieved.')}</p>:<HighlightedText text={loaded||t('Wczytywanie…','Loading…')} quote={quote}/>}</div>;}
function HighlightedText({text,quote}: {text:string;quote?:string}) {const index=quote?text.indexOf(quote):-1;return <pre className="source-text" tabIndex={0}>{index<0?text:<>{text.slice(0,index)}<mark>{quote}</mark>{text.slice(index+quote!.length)}</>}</pre>;}
function PdfPage({url,pageNumber,bbox}: {url:string;pageNumber:number;bbox?:number[]}) {
  const canvas=useRef<HTMLCanvasElement>(null);const container=useRef<HTMLDivElement>(null);const [error,setError]=useState<unknown>(null);const [loading,setLoading]=useState(true);const {t}=useLang();
  useEffect(()=>{let cancelled=false;let destroy:(()=>void)|undefined;setLoading(true);setError(null);void(async()=>{try{const pdfjs=await import('pdfjs-dist');const worker=await import('pdfjs-dist/build/pdf.worker.min.mjs?url');if(cancelled)return;pdfjs.GlobalWorkerOptions.workerSrc=worker.default;const task=pdfjs.getDocument({url,withCredentials:true});destroy=()=>{void task.destroy();};const pdf=await task.promise;if(cancelled)return;const page=await pdf.getPage(Math.min(pageNumber,pdf.numPages));if(cancelled||!canvas.current)return;const base=page.getViewport({scale:1});const scale=Math.min((container.current?.clientWidth||600)/base.width,1.7);const viewport=page.getViewport({scale});const pixelRatio=Math.min(window.devicePixelRatio||1,2);canvas.current.width=Math.round(viewport.width*pixelRatio);canvas.current.height=Math.round(viewport.height*pixelRatio);canvas.current.style.width=`${viewport.width}px`;canvas.current.style.height=`${viewport.height}px`;const context=canvas.current.getContext('2d')!;await page.render({canvas:canvas.current,canvasContext:context,viewport,transform:pixelRatio!==1?[pixelRatio,0,0,pixelRatio,0,0]:undefined}).promise;if(bbox?.length===4){context.save();context.scale(pixelRatio*scale,pixelRatio*scale);context.fillStyle='rgba(255,207,61,.28)';context.strokeStyle='#c08700';context.lineWidth=1;context.fillRect(bbox[0],bbox[1],bbox[2]-bbox[0],bbox[3]-bbox[1]);context.strokeRect(bbox[0],bbox[1],bbox[2]-bbox[0],bbox[3]-bbox[1]);context.restore();}if(!cancelled)setLoading(false);}catch(e){if(!cancelled){setError(e);setLoading(false);}}})();return()=>{cancelled=true;destroy?.();};},[url,pageNumber,bbox]);
  return <div className="pdf-preview" ref={container}>{loading?<p role="status">{t('Wczytywanie strony PDF…','Loading the PDF page…')}</p>:null}{error?<ErrorBox error={error}/>:null}<canvas ref={canvas} aria-label={`${t('Strona dokumentu','Document page')} ${pageNumber}`} role="img"/><p className="small muted">{t('Strona','Page')} {pageNumber}. {bbox?.length?t('Położenie fragmentu wskazane podczas odczytu dokumentu.','Passage location identified while reading the document.'):t('Brak dokładnego prostokąta: porównaj cytat z całą stroną.','No exact bounding box: compare the quote with the full page.')}</p></div>;
}
