import { useState } from 'react';
import { ArrowRight, Check, CircleHelp, MessageSquareText, Send, UserRound } from 'lucide-react';
import { Badge, Button, Checkbox, CopyButton, Empty, ErrorBox, Fold, SectionHeading, money, offerCode, personName, issueText, statusLabel, useLang } from './ui';
import { ScenarioExplorer, WitnessView } from './Comparison';
import type { CaseDetail, MutateCase, Question } from './types';

export function Questions({data,mutate,readOnly,publicDemo,onReview}: {data:CaseDetail;mutate:MutateCase;readOnly:boolean;publicDemo:boolean;onReview:()=>void}) {
  const {t,lang}=useLang();
  const questions=(data.questions?.length?data.questions:data.analysis?.questions)||[];
  const [selected,setSelected]=useState<string|null>(null);
  const question=questions.find(q=>q.id===selected)||questions.find(q=>q.needed)||questions[0];
  if(!question)return <Empty title={t('Na razie nie ma pytań do wyjaśnienia','There are no questions to clarify yet')}>{t('Pytania wynikają z niewiadomych w analizie. Brak pytań sam w sobie nie oznacza kompletnej analizy.','Questions come from unknowns in the analysis. An absence of questions alone does not indicate completeness.')}</Empty>;
  const engineQuestion=data.analysis?.questions?.find(q=>q.id===question.id);
  const witness=question.witness||engineQuestion?.witness;
  const outcomes=witness?.scenarios?.slice(0,2).map(scenario=>{
    const conditions=Object.entries(scenario.assignment||{}).map(([id,value])=>{const variable=data.model?.variables?.find(v=>v.id===id);return `${variable?.label||id}: ${variable?.unit==='minor'?money(Number(value),String(data.requirements.currency||'PLN'),lang):String(value)}`;}).join(', ');
    const winners=scenario.winners?.map(id=>offerCode(data.offers,id)).join(', ');
    return `${conditions}. ${winners?t('Najtańsza oferta spełniająca wymagania','Lowest-cost offer meeting requirements')+': '+winners:t('Brak oferty spełniającej wymagania','No offer meets the requirements')}.`;
  }).join(' ');
  return <div className="stack-lg"><SectionHeading eyebrow={t('NAJPIERW TO, CO ZMIENIA WYNIK','START WITH WHAT CHANGES THE RESULT')} title={t('Co trzeba jeszcze wyjaśnić?','What still needs clarification?')}>{t('Kolejność wynika z opisanych scenariuszy. Możesz wybrać inne pytanie i zapisać odpowiedź „nie wiem”.','The order follows the described scenarios. You can choose another question and record “I don’t know”.')}</SectionHeading>
    <div className="question-layout"><aside className="question-list" aria-label={t('Lista pytań','Question list')}>{questions.map((q,i)=><button key={q.id} onClick={()=>setSelected(q.id)} className={`question-select ${q.id===question.id?'selected':''}`}><span className="question-number">{String(i+1).padStart(2,'0')}</span><span><strong>{issueText(q.text,data.facts,data.offers,t)}</strong><small>{q.needsReview?t('Do ponownego sprawdzenia','Needs review'):statusLabel(q.status||'prepared',t)}</small></span><ArrowRight size={16}/></button>)}</aside>
      <section className="card question-detail"><div className="inline wrap spread"><Badge tone="blue"><MessageSquareText size={13}/>{question.kind==='model_gap'?t('Do sprawdzenia w dokumentach','Review the documents'):t('Pytanie do wykonawcy','Question for the supplier')}</Badge><Badge tone={question.status==='resolved'?'good':'warn'}>{statusLabel(question.status||'prepared',t)}</Badge></div><h3 className="question-text">{issueText(question.text,data.facts,data.offers,t)}</h3><div className="inline wrap"><CopyButton text={issueText(question.text,data.facts,data.offers,t)}/><span className="small muted">{t('Udostępniasz samodzielnie. Aplikacja nie wysyła wiadomości.','You share it yourself. The app does not send messages.')}</span></div>
        {question.needsReview?<div className="notice warning"><CircleHelp size={20}/><div><strong>{t('Sprawdź odpowiedź po zmianie materiałów','Review the reply after the source change')}</strong><p>{t('Poprzednia odpowiedź pozostała w historii. Sprawdź nowe materiały i zapisz aktualną, potwierdzoną odpowiedź.','The previous reply is preserved in history. Review the new sources and record a current, confirmed reply.')}</p>{question.reviewReason?<p className="small">{question.reviewReason}</p>:null}</div></div>:null}
        <div className="why-question"><CircleHelp size={19}/><div><strong>{t('Dlaczego to pytanie?','Why this question?')}</strong><p>{engineQuestion?.needed===false?t('Wspólny najtańszy wybór już istnieje. To pytanie nie jest niezbędne do wyboru w obecnym modelu.','A common lowest-cost choice already exists. This question is not essential for choosing in the current model.'):witness?.kind==='winner_change'?(outcomes||t('Odpowiedź zmienia najtańszą ofertę spełniającą wymagania. Porównaj warianty poniżej.','The reply changes the lowest-cost offer meeting requirements. Compare the alternatives below.')):t('Odpowiedź doprecyzuje brak lub warunek w modelu. Siła wpływu zależy od kompletności danych.','The answer clarifies a gap or condition in the model. Its impact depends on data completeness.')}</p></div></div>
        {witness?<WitnessView witness={witness} data={data}/>:null}
        <QuestionBranches question={engineQuestion||question} data={data}/>
        <Fold title={t('Jak wybrano kolejność pytań?','How are questions ordered?')}><p>{t('Heurystyka wybiera pytanie z najmniejszą niejednoznacznością w najgorszej informacyjnej gałęzi. Uwzględnia wspólnego współzwycięzcę, a przy remisie deklarowaną trudność odpowiedzi. Nie zakłada prawdopodobieństw.','The heuristic chooses the question with the least ambiguity in the worst informative branch. It considers a common co-winner and declared difficulty for tie breaking. It assumes no probabilities.')}</p><p className="small">{t('Wynik heurystyki','Heuristic score')}: {engineQuestion?.score??question.score??t('Jeszcze nieobliczony','Not calculated yet')}</p></Fold>
        {!readOnly?<QuestionControls key={`${question.id}-${data.revision}`} question={question} data={data} mutate={mutate} onReview={onReview}/>:<div className="notice"><InfoIcon/><p>{publicDemo?t('Oglądasz zapisany, fikcyjny przykład. Sprawdź wpływ różnych odpowiedzi w kalkulatorze poniżej. Dodawanie źródeł i zapisywanie decyzji jest dostępne w pełnej aplikacji po zalogowaniu.','You are viewing a recorded, fictional example. Explore different answers in the calculator below. Adding sources and saving decisions is available in the full signed-in application.'):t('Masz dostęp tylko do odczytu.','You have read-only access.')}</p></div>}
        {question.answers?.length?<div className="answers"><h4>{t('Zapisane odpowiedzi','Recorded answers')}</h4>{question.answers.map((answer,i)=><blockquote key={answer.id||i}>{answer.needsReview?<Badge tone="warn">{t('Odpowiedź historyczna, wymaga ponownego sprawdzenia','Historical reply, requires review')}</Badge>:null}<p>{answer.text}</p>{answer.needsReview&&answer.reviewReason?<p className="small muted">{answer.reviewReason}</p>:null}<footer>{personName(data.members,answer.author,t)} · {answer.kind==='unknown'?t('Nie zmniejsza zbioru scenariuszy','Does not reduce the scenario set'):t('Odpowiedź jako źródło','Answer recorded as a source')}</footer></blockquote>)}</div>:null}
      </section>
    </div><ScenarioExplorer data={data} publicDemo={publicDemo}/>
  </div>;
}
function InfoIcon(){return <CircleHelp size={20}/>;}
function QuestionBranches({question,data}: {question:Question;data:CaseDetail}) {
  const {t,lang}=useLang();const branches=(question.branches||[]) as Array<{answers:Record<string,unknown>;scenario_count:number;common_winners:string[];all_infeasible:boolean}>;
  if(!branches.length)return null;
  return <Fold title={t('Dopuszczalne odpowiedzi i ich skutki','Admissible answers and their outcomes')}><div className="stack"><p className="small muted">{question.branches_truncated_for_display?t(`Wszystkich gałęzi: ${String(question.branch_count)}. Tabela pokazuje ${branches.length}; wynik i ranking obliczono dla całości.`,`Total branches: ${String(question.branch_count)}. This table shows ${branches.length}; the result and ranking use all branches.`):t('Tabela dotyczy zapisanej dziedziny. Nowa odpowiedź może ją rozszerzyć po sprawdzeniu.','This table covers the recorded domain. A new answer may extend it after review.')}</p><div className="table-scroll"><table className="simple-table"><thead><tr><th scope="col">{t('Odpowiedź','Answer')}</th><th scope="col">{t('Wspólny wybór','Common choice')}</th><th scope="col">{t('Scenariusze','Scenarios')}</th></tr></thead><tbody>{branches.map((branch,i)=><tr key={i}><th scope="row">{Object.entries(branch.answers).map(([id,value])=>{const variable=data.model?.variables?.find(v=>v.id===id);return <div key={id}>{variable?.label||id}: {variable?.unit==='minor'?money(Number(value),String(data.requirements.currency||'PLN'),lang):typeof value==='boolean'?(value?t('Tak','Yes'):t('Nie','No')):String(value)}</div>;})}</th><td>{branch.all_infeasible?t('Brak wykonalnej oferty','No feasible offer'):branch.common_winners?.map(id=>offerCode(data.offers,id)).join(', ')||t('Potrzebne kolejne wyjaśnienie','Further clarification needed')}</td><td>{branch.scenario_count}</td></tr>)}</tbody></table></div></div></Fold>;
}
function QuestionControls({question,data,mutate,onReview}: {question:Question;data:CaseDetail;mutate:MutateCase;onReview:()=>void}) {
  const {t}=useLang();const [text,setText]=useState('');const [values,setValues]=useState<Record<string,string>>({});const [kind,setKind]=useState<'value'|'unknown'>('value');const [confirmed,setConfirmed]=useState(false);const [error,setError]=useState<unknown>(null);const [busy,setBusy]=useState(false);const [assignee,setAssignee]=useState(question.assignee||'');const [dueAt,setDueAt]=useState(question.dueAt?.slice(0,10)||'');const [difficulty,setDifficulty]=useState(question.difficulty??0);
  const ids=question.variable_ids?.length?question.variable_ids:[question.variable_id||question.id];
  const variables=(data.model?.variables||[]).filter(v=>ids.includes(v.id));
  const perform=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError(null);try{await fn();}catch(e){setError(e);}finally{setBusy(false);}};
  const answerValue=()=>{const parsed:Record<string,unknown>={};for(const variable of variables){const raw=values[variable.id]||'';const numeric=variable.unit==='minor'||variable.kind==='interval'||variable.values?.some(v=>typeof v==='number');parsed[variable.id]=variable.unit==='minor'?Math.round(Number(raw)*100):raw==='true'?true:raw==='false'?false:numeric?Number(raw):raw;if(numeric&&!Number.isFinite(Number(parsed[variable.id])))throw new Error(t('Podaj poprawną wartość liczbową.','Enter a valid numeric value.'));}return variables.length===1?parsed[variables[0].id]:parsed;};
  return <div className="question-controls stack"><Fold title={t('Status, odpowiedzialność i termin','Status, assignee and due date')}><div className="form-grid"><label className="field"><span>{t('Osoba odpowiedzialna','Assignee')}</span><input value={assignee} onChange={e=>setAssignee(e.target.value)} placeholder={t('Imię lub adres kontaktowy','Name or contact address')}/></label><label className="field"><span>{t('Termin wyjaśnienia','Clarification due date')}</span><input type="date" value={dueAt} onChange={e=>setDueAt(e.target.value)}/></label><label className="field"><span>{t('Trudność odpowiedzi (0–10)','Answer difficulty (0–10)')}</span><input type="number" min="0" max="10" value={difficulty} onChange={e=>setDifficulty(Number(e.target.value))}/></label></div><div className="inline wrap"><Button variant="secondary" busy={busy} onClick={()=>perform(()=>mutate(`/questions/${question.id}`,{status:question.status||'prepared',assignee,dueAt:dueAt||null,difficulty},'PATCH'))}><UserRound size={16}/>{t('Zapisz odpowiedzialność','Save assignment')}</Button><Button variant="secondary" busy={busy} onClick={()=>perform(()=>mutate(`/questions/${question.id}`,{status:'waiting',assignee,dueAt:dueAt||null,difficulty},'PATCH'))}><Send size={16}/>{t('Oznacz: oczekuje na odpowiedź','Mark as awaiting a reply')}</Button></div><p className="small muted">{t('Oczekiwanie jest Twoją deklaracją. Nie potwierdza wysłania wiadomości przez system.','Awaiting is your declaration. It does not confirm a message was sent by the system.')}</p></Fold>
    <h4>{t('Dodaj otrzymaną odpowiedź','Add the reply you received')}</h4><div className="segmented"><button className={kind==='value'?'active':''} onClick={()=>setKind('value')}>{t('Mam odpowiedź','I have an answer')}</button><button className={kind==='unknown'?'active':''} onClick={()=>setKind('unknown')}>{t('Nie wiem','I don’t know')}</button></div>
    <label className="field"><span>{kind==='unknown'?t('Kontekst braku odpowiedzi','Context for the missing answer'):t('Oryginalna treść odpowiedzi i autor','Original reply text and author')}</span><textarea value={text} onChange={e=>setText(e.target.value)} placeholder={t('Wklej odpowiedź wykonawcy lub zapisz własne ustalenie z autorem.','Paste the supplier’s reply or record your own finding with its author.')}/></label>
    {kind==='value'?<>{!variables.length?<div className="notice warning"><div><p>{t('Ten brak wymaga poprawienia źródła lub modelu. Otwórz przegląd i dodaj uzasadnioną korektę.','This gap needs a source or model correction. Open review and add a correction with a rationale.')}</p><Button variant="secondary" onClick={onReview}>{t('Otwórz przegląd','Open review')}</Button></div></div>:null}{variables.map(variable=>{const money=variable.unit==='minor';const numeric=money||variable.kind==='interval'||variable.values?.some(v=>typeof v==='number');const boolean=variable.values?.length&&variable.values.every(v=>typeof v==='boolean');return <label className="field" key={variable.id}><span>{variable.label||variable.id}{money?` (${data.requirements.currency||'PLN'})`:variable.unit?` (${variable.unit})`:''}</span>{boolean?<select value={values[variable.id]||''} onChange={e=>setValues(prev=>({...prev,[variable.id]:e.target.value}))}><option value="">{t('Wybierz odpowiedź','Choose an answer')}</option><option value="true">{t('Tak','Yes')}</option><option value="false">{t('Nie','No')}</option></select>:<input type={numeric?'number':'text'} step={money?'0.01':'any'} value={values[variable.id]||''} onChange={e=>setValues(prev=>({...prev,[variable.id]:e.target.value}))}/>}<small className="muted">{t('Nowa wartość może wykraczać poza początkową dziedzinę. Zostanie zapisana w nowej wersji.','A new value may be outside the original domain. It will be recorded in a new version.')}</small></label>;})}<Checkbox checked={confirmed} onChange={setConfirmed}>{t('Sprawdziłem treść, autora i przypisanie odpowiedzi. Potwierdzam tę interpretację.','I have reviewed the text, author and assignment of this reply. I confirm this interpretation.')}</Checkbox></>:<p className="small">{t('„Nie wiem” zachowuje niewiadomą i wszystkie dopuszczalne scenariusze.','“I don’t know” preserves the unknown and all admissible scenarios.')}</p>}
    {error?<ErrorBox error={error}/>:null}<Button busy={busy} disabled={kind==='value'&&(!confirmed||!text.trim()||!variables.length||variables.some(v=>!values[v.id]?.trim()))} onClick={()=>perform(()=>mutate(`/questions/${question.id}/answers`,{text:text.trim()||(kind==='unknown'?t('Nie wiem','I don’t know'):''),kind,...(kind==='value'?{value:answerValue()}:{}),confirmed:kind==='value'&&confirmed}))}><Check size={17}/>{t('Zapisz odpowiedź i przelicz','Save reply and recalculate')}</Button>
  </div>;
}
