import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Sparkles, Check, CalendarDays, Wallet, Users, Clock3 } from 'lucide-react';
import { api, displayTime } from './api';
import { Button, Checkbox, ErrorBox, useLang, money } from './ui';
import type { Requirement } from './types';
import { localParts, zonedInstant } from './dates';

const schema=z.object({title:z.string().min(3).max(160),scope:z.string().min(3),participants:z.number().int().min(1),microphones:z.number().int().min(0),event_date:z.string().min(1),service_end_date:z.string().min(1),ready_date:z.string().min(1),service_start:z.string().min(1),service_end:z.string().min(1),ready_by:z.string().min(1),budget:z.number().positive(),currency:z.string().length(3),timezone:z.string().min(1),preferences:z.string()});
type Fields=z.infer<typeof schema>;
export function RequirementsForm({title='',requirements={},onSave,onPropose,busy=false}: {title?:string;requirements?:Requirement;onSave:(title:string,requirements:Requirement)=>Promise<unknown>;onPropose?:(text:string)=>Promise<{requirements:Requirement}>;busy?:boolean}) {
  const {t}=useLang();
  const [confirmed,setConfirmed]=useState(false);
  const [description,setDescription]=useState('');
  const [proposalBusy,setProposalBusy]=useState(false);
  const [proposalInfo,setProposalInfo]=useState(false);
  const [error,setError]=useState<unknown>(null);
  const zone=String(requirements.timezone||'Europe/Warsaw');const start=localParts(requirements.service_start,zone);const end=localParts(requirements.service_end,zone);const ready=localParts(requirements.ready_by,zone);const date=String(requirements.event_date||start.date||new Date().toISOString().slice(0,10));
  const {register,handleSubmit,setValue,formState:{errors,isSubmitting}}=useForm<Fields>({resolver:zodResolver(schema),defaultValues:{title,scope:String(requirements.scope||requirements.description||''),participants:requirements.participants||120,microphones:requirements.microphones??4,event_date:date,service_end_date:end.date||date,ready_date:ready.date||date,service_start:start.time||'09:00',service_end:end.time||'17:00',ready_by:ready.time||'09:00',budget:Number(requirements.budget_minor||560000)/100,currency:String(requirements.currency||'PLN'),timezone:zone,preferences:String(requirements.preferences||'')}});
  const field=(name:keyof Fields,label:string,type='text',extra:Record<string,unknown>={})=><label className="field" key={name}><span>{label}</span><input type={type} aria-invalid={Boolean(errors[name])} {...register(name,{valueAsNumber:type==='number',...(name==='event_date'?{onChange:(e:React.ChangeEvent<HTMLInputElement>)=>{setValue('service_end_date',e.target.value);setValue('ready_date',e.target.value);}}:{})})} {...extra}/>{errors[name]?<small className="field-error">{t('Sprawdź wartość tego pola.','Please check this value.')}</small>:null}</label>;
  return <form onSubmit={handleSubmit(async data=>{setError(null);try{const {budget,title:caseTitle,service_end_date,ready_date,...rest}=data;await onSave(caseTitle,{...rest,description:rest.scope,scope_required:true,currency:rest.currency.toUpperCase(),service_start:zonedInstant(rest.event_date,rest.service_start,rest.timezone),service_end:zonedInstant(service_end_date,rest.service_end,rest.timezone),ready_by:zonedInstant(ready_date,rest.ready_by,rest.timezone),budget_minor:Math.round(budget*100),confirmed});}catch(e){setError(e);}})} className="stack">
    {onPropose?<div className="proposal-box"><div className="inline"><Sparkles size={18}/><strong>{t('Zacznij od opisu','Start with a description')}</strong></div><p>{t('AI może zaproponować wymagania. Przed zapisem sprawdź każde pole. Opis zostanie przekazany do Google Gemini.','AI can propose requirements. Check every field before saving. Your description will be sent to Google Gemini.')}</p><label className="field"><span>{t('Opis wydarzenia dla AI','Event description for AI')}</span><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder={t('Konferencja dla 120 osób, cztery mikrofony, technik od 9 do 17…','A conference for 120 people, four microphones, technician from 9 to 17…')}/></label><Button type="button" variant="secondary" busy={proposalBusy} disabled={!description.trim()} onClick={async()=>{setProposalBusy(true);setError(null);try{const result=await onPropose(description);for(const [key,value] of Object.entries(result.requirements)){if(key==='budget_minor')setValue('budget',Number(value)/100);else if(['service_start','service_end','ready_by'].includes(key)){const part=localParts(value,String(result.requirements.timezone||zone));setValue(key as keyof Fields,part.time);if(key==='service_start')setValue('event_date',part.date);if(key==='service_end')setValue('service_end_date',part.date);if(key==='ready_by')setValue('ready_date',part.date);}else if(key==='description')setValue('scope',String(value||''));else if(value!=null&&key in schema.shape)setValue(key as keyof Fields,value as never);}setProposalInfo(true);setConfirmed(false);}catch(e){setError(e);}finally{setProposalBusy(false);}}}><Sparkles size={16}/>{t('Zaproponuj pola','Suggest fields')}</Button>{proposalInfo?<p role="status">{t('Pola uzupełniono propozycją. Sprawdź zakres, datę i twarde ograniczenia.','Fields contain a proposal. Check the scope, date and hard constraints.')}</p>:null}</div>:<p className="small muted">{t('Po zapisaniu sprawy możesz także skorzystać z propozycji wymagań z opisu AI.','After saving the case, you can also ask AI to suggest requirements from a description.')}</p>}
    <div className="form-grid">{field('title',t('Nazwa sprawy','Case name'))}{field('event_date',t('Data wydarzenia','Event date'),'date')}</div>
    <label className="field"><span>{t('Pełny wymagany zakres','Full required scope')}</span><textarea {...register('scope')} placeholder={t('Nagłośnienie sali, montaż, transport i obsługa techniczna','Sound system, setup, transport and technical service')}/>{errors.scope?<small className="field-error">{t('Opisz wymagany zakres.','Describe the required scope.')}</small>:null}</label>
    <div className="form-grid">{field('participants',t('Uczestnicy','Participants'),'number',{min:1})}{field('microphones',t('Mikrofony bezprzewodowe','Wireless microphones'),'number',{min:0})}{field('service_start',t('Początek obsługi','Service starts'),'time')}{field('service_end',t('Koniec obsługi','Service ends'),'time')}{field('service_end_date',t('Data końca obsługi (także następny dzień)','Service end date (including next day)'),'date')}{field('ready_date',t('Data gotowości','Readiness date'),'date')}{field('ready_by',t('Gotowość najpóźniej','Ready no later than'),'time')}{field('timezone',t('Strefa czasowa','Time zone'))}{field('budget',t('Budżet brutto','Gross budget'),'number',{step:'0.01',min:'0.01'})}{field('currency',t('Waluta (kod ISO)','Currency (ISO code)'))}</div>
    <label className="field"><span>{t('Preferencje jakościowe (osobno od ograniczeń)','Quality preferences (separate from constraints)')}</span><textarea {...register('preferences')} placeholder={t('Np. doświadczenie w wydarzeniach hybrydowych','For example, experience with hybrid events')}/></label>
    <div className="notice"><strong>{t('Jawna reguła wyboru','An explicit selection rule')}</strong><p>{t('Porównujemy minimalny pełny koszt ofert spełniających wymagania. Liczba uczestników i mikrofonów nie dowodzi wystarczalności nagłośnienia. Zakres musi mieć osobne potwierdzenie.','We compare the lowest full cost among offers meeting requirements. Participant and microphone counts do not prove sound-system suitability. Scope needs separate confirmation.')}</p></div>
    <Checkbox checked={confirmed} onChange={setConfirmed}>{t('Sprawdziłem zakres i zatwierdzam te twarde ograniczenia.','I have reviewed the scope and approve these hard constraints.')}</Checkbox>
    {error?<ErrorBox error={error}/>:null}<Button busy={busy||isSubmitting} type="submit" disabled={!confirmed}><Check size={17}/>{t('Zapisz wymagania','Save requirements')}</Button>
  </form>;
}
export function RequirementStrip({requirements,onEdit,readOnly=false}: {requirements:Requirement;onEdit?:()=>void;readOnly?:boolean}) {
  const {t,lang}=useLang();
  return <div className="requirements-strip"><div><Users size={17}/><span><b>{requirements.participants??'?'}</b> {t('uczestników','participants')}</span></div><div><CalendarDays size={17}/><span>{String(requirements.event_date||localParts(requirements.service_start,String(requirements.timezone||'Europe/Warsaw')).date||t('Data do ustalenia','Date to confirm'))}</span></div><div><Clock3 size={17}/><span>{displayTime(requirements.service_start,String(requirements.timezone||'Europe/Warsaw'))}–{displayTime(requirements.service_end,String(requirements.timezone||'Europe/Warsaw'))} <small>{String(requirements.timezone||'Europe/Warsaw')}</small></span></div><div><Wallet size={17}/><span><b>{money(requirements.budget_minor,String(requirements.currency||'PLN'),lang)}</b> {t('brutto','gross')}</span></div>{onEdit?<button className="text-link" onClick={onEdit}>{readOnly?t('Wymagania','Requirements'):t('Edytuj','Edit')}</button>:null}</div>;
}
