import type { components } from './generated-api';
export type ApiSchemas = components['schemas'];
export type Lang = 'pl' | 'en';
export type Translate = (pl: string, en: string) => string;
export type Datum = string | number | boolean | null | Record<string, unknown> | unknown[];
export type Requirement = {
  scope?: string; participants?: number; microphones?: number; event_date?: string;
  ready_by?: string; service_start?: string; service_end?: string; timezone?: string;
  budget_minor?: number; currency?: string; preferences?: string; [key: string]: unknown;
};
export type Evidence = {id?: string; source_id?:string; document_id?: string; documentId?: string; page?: number; quote?: string; bbox?: number[]; method?: string; citation_valid?: boolean; [key: string]: unknown};
export type Fact = {id: string; offer_id?: string; offerId?: string; field?: string; label?: string; value: Datum; unit?: string; condition?: string; scope?: string; evidence?: Evidence[]; evidence_ids?: string[]; confirmation?: string; status?: string; critical?: boolean; reason?: string; author?: string; provenance?: string; [key: string]: unknown};
export type DocumentRecord = {id: string; name?: string; filename?: string; offer_id?: string; offerId?: string; mime?: string; mime_type?: string; hash?: string; sha256?: string; version?: number; author?: string; documentDate?: string; createdAt?: string; relation?: string; relation_confirmed?: boolean; pages?: Array<{page?: number; number?:number; status?: string; text?: string; method?: string}>; page_count?: number; status?: string; text?: string; url?: string; [key: string]: unknown};
export type CostItem = {id: string; label: string; amount: Record<string, unknown>; category: string; evidence_ids?: string[]};
export type Offer = {id: string; name: string; currency?: string; tax_basis?: string; cost_items?: CostItem[]; participants?: number; microphones?: number; ready_at?: string; service_start?: string; service_end?: string; scope_confirmed?: boolean; evidence_ids?: string[]; [key: string]: unknown};
export type Variable = {id: string; label: string; kind: string; values?: Datum[]; lower?: number; upper?: number; complete?: boolean; unit?: string; question?: string; [key: string]: unknown};
export type Scenario = {id: string; assignment: Record<string, Datum>; costs: Record<string, number>; feasible: string[]; winners: string[]; exclusions: Record<string, Array<{code: string; message: string}>>; breakdown: Record<string, Array<{id: string; label: string; category: string; amount_minor: number; evidence_ids?: string[]}>>};
export type OfferResult = {id: string; name: string; min_cost_minor: number | null; max_cost_minor: number | null; always_feasible: boolean; sometimes_feasible: boolean; possible_winner: boolean; common_winner: boolean; exclusions?: Array<{code: string; message: string}>};
export type Witness = {kind: string; scenarios: Scenario[]; changed_variables: string[]};
export type Question = {id: string; variable_ids?: string[]; variable_id?: string; text: string; score?: number; needed?: boolean; branches?: unknown[]; witness?: Witness; status?: string; assignee?: string; dueAt?: string; difficulty?: number; needsReview?: boolean; reviewReason?: string; answers?: Array<{id?: string; text: string; kind?: string; value?: Datum; author?: string; createdAt?: string; confirmed?: boolean; needsReview?: boolean; reviewReason?: string}>; [key: string]: unknown};
export type Analysis = {status: string; complete: boolean; scenario_count: number; scenarios: Scenario[]; offers: OfferResult[]; robust_feasible: string[]; common_winners: string[]; unique_winner?: string; questions: Question[]; witnesses?: Witness[]; thresholds?: Array<{variable_id: string; value: number; kind: string; offer_ids?: string[]}>; issues?: Array<{code: string; message: string}>; [key: string]: unknown};
export type Job = {id: string; status: string; stage?: string; completed_pages?: number; total_pages?: number; error?: string; message?: string; [key: string]: unknown};
export type Decision = {id: string; offerId?: string; offer_id?: string; revision?: number; kind: string; status?: string; reason?: string; assumptions?: string; nextStep?: string; owner?: string; author?: string; createdAt?: string; [key: string]: unknown};
export type Member = {id?: string; userId?: string; name?: string; email?: string; role: string};
export type AuditEvent = {id?: string; revision?: number; type?: string; action?: string; createdAt?: string; author?: string; summary?: string; [key: string]: unknown};
export type CaseDetail = Omit<ApiSchemas['CaseDetail'], 'requirements'|'model'|'offers'|'documents'|'facts'|'questions'|'analysis'|'decisions'|'history'|'members'|'jobs'|'approval'|'impact'> & {id: string; title: string; revision: number; status?: string; requirements: Requirement; model?: {offers?: Offer[]; variables?: Variable[]; currency?: string; budget_minor?: number; requirements?: Requirement; [key: string]: unknown}; offers: Offer[]; documents: DocumentRecord[]; facts: Fact[]; questions: Question[]; analysis: Analysis | null; decisions: Decision[]; history: AuditEvent[]; members: Member[]; jobs: Job[]; role: string; approval?: Record<string, unknown> | null; impact?: Array<Record<string,unknown>>; pendingAnalysis?: boolean; [key: string]: unknown};
export type Auth = {user: {id: string; name: string; email: string} | null; csrfToken: string | null; authMode: string; guestEnabled?: boolean};
export type CaseSummary = {id: string; title: string; revision: number; status: string; updatedAt: string; role: string};
export type MutateCase = (path: string, body?: Record<string, unknown> | FormData, method?: string) => Promise<unknown>;
