import { useState } from 'react';
import { Check, FileCheck2, FileSearch, Download, History, RotateCcw, Share2, Trash2, Users, AlertTriangle, ArrowRight, ShieldCheck } from 'lucide-react';
import { Badge, Button, Checkbox, CopyButton, Empty, ErrorBox, Fold, Modal, SectionHeading, money, factLabel, factDisplay, offerCode, offerName, personName, statusLabel, useLang } from './ui';
import { demoOnly, displayTime, navigate, valueText } from './api';
import { ModelEditor } from './ModelEditor';
import type { CaseDetail, Fact, MutateCase } from './types';

export function Review({data,mutate,onEvidence,readOnly}: {data:CaseDetail;mutate:MutateCase;onEvidence:(fact:Fact)=>void;readOnly:boolean}) {
  const {t,lang}=useLang();const [selected,setSelected]=useState<string[]>([]);const [requirements,setRequirements]=useState(false);const [error,setError]=useState<unknown>(null);const [busy,setBusy]=useState(false);const facts=data.facts.filter(f=>f.critical!==false);
  
  return <div className="stack-lg"><SectionHeading eyebrow={t('KONTROLA PO TWOJEJ STRONIE','YOU STAY IN CONTROL')} title={t('Sprawdź to, na czym opiera się decyzja','Review what the decision relies on')}>{t('Potwierdzasz konkretne wartości i ich zakres. Pochodzenie, zgodność cytatu i interpretacja są osobnymi informacjami.','You confirm specific values and their scope. Provenance, quote validation and interpretation remain separate.')}</SectionHeading>
    {data.impact?.length?<Impact data={data}/>:null}
    <ModelEditor key={`model-${data.revision}`} data={data} mutate={mutate} readOnly={readOnly}/>
    <div className="review-list">{facts.map(fact=><article className="card review-fact" key={fact.id}><div className="review-main"><span className="offer-letter small-letter" role="img" aria-label={offerName(data.offers,fact.offer_id||fact.offerId)} title={offerName(data.offers,fact.offer_id||fact.offerId)}>{offerCode(data.offers,fact.offer_id||fact.offerId)}</span><div><h3>{factLabel(fact,t)}</h3><strong className="review-value" tabIndex={0}>{factDisplay(fact,t,lang,String(data.requirements.currency||'PLN'),String(data.requirements.timezone||'Europe/Warsaw'))}</strong>{fact.condition?<p className="small muted">{t('Warunek','Condition')}: {valueText(fact.condition)}</p>:null}{fact.scope?<p className="small muted">{t('Zakres','Scope')}: {valueText(fact.scope)}</p>:null}</div></div><div className="review-meta"><Badge tone={fact.confirmation==='confirmed'?'good':'warn'}>{statusLabel(fact.confirmation||'proposed',t)}</Badge><button className="text-link" onClick={()=>onEvidence(fact)}><FileSearch size={16}/>{t('Porównaj z oryginałem','Compare with original')}</button><span className="small muted">{t('Dowody','Evidence')}: {fact.evidence?.length||0}</span></div>{!readOnly?<Checkbox checked={selected.includes(fact.id)} onChange={checked=>setSelected(prev=>checked?[...prev,fact.id]:prev.filter(id=>id!==fact.id))}>{t('Potwierdzam wartość, zakres i interpretację','I confirm the value, scope and interpretation')}</Checkbox>:null}</article>)}</div>
    {!readOnly?<div className="card approval-box"><h3>{t('Zatwierdzenie przeglądu dla wersji','Review approval for version')} {data.revision}</h3><p>{t('Wybrane pola zostaną przypisane do aktualnych zależności. Zmiana źródła odnowi tylko zależne potwierdzenia, a niepewny wpływ skieruje cały wynik do przeglądu.','Selected fields will be linked to current dependencies. A source change renews dependent confirmations; uncertain impact requires review of the whole result.')}</p><Checkbox checked={requirements} onChange={setRequirements}>{t('Potwierdzam aktualne wymagania, termin, budżet i zgodność porównywanego zakresu.','I confirm the current requirements, deadline, budget and comparable scope.')}</Checkbox>{error?<ErrorBox error={error}/>:null}<Button busy={busy} disabled={!requirements} onClick={async()=>{setBusy(true);setError(null);try{await mutate('/approvals',{factIds:selected,requirementsConfirmed:requirements});setSelected([]);setRequirements(false);}catch(e){setError(e);}finally{setBusy(false);}}}><ShieldCheck size={17}/>{t('Zatwierdź wybrane pola','Approve selected fields')} ({selected.length})</Button></div>:null}
  </div>;
}
export function Impact({data}: {data:CaseDetail}) {const {t}=useLang();return <div className="notice warning impact"><AlertTriangle size={22}/><div><strong>{t('Co wymaga ponownego sprawdzenia','What needs to be reviewed again')}</strong>{data.impact?.map((impact,i)=><div key={i}><p>{String(impact.reason||t('Nowe źródła zmieniły zależności wyniku.','New sources have changed the result’s dependencies.'))}</p><ul>{Array.isArray(impact.factIds)&&impact.factIds.length?impact.factIds.map(id=>{const fact=data.facts.find(f=>f.id===String(id));return <li key={String(id)}>{fact?`${offerName(data.offers,fact.offer_id||fact.offerId)}: ${factLabel(fact,t)}`:t('Ustalenie z wcześniejszej wersji','Finding from an earlier version')}</li>;}):<li>{t('Wynik i aktualność wcześniejszych decyzji','The result and validity of previous decisions')}</li>}</ul></div>)}</div></div>;}
export function DecisionPanel({data,mutate,readOnly,publicDemo,onReview}: {data:CaseDetail;mutate:MutateCase;readOnly:boolean;publicDemo:boolean;onReview:()=>void}) {
  const {t,lang}=useLang();const [offerId,setOfferId]=useState(data.analysis?.unique_winner||data.analysis?.common_winners?.[0]||data.offers[0]?.id||'');const [kind,setKind]=useState<'final'|'conditional'>('final');const [reason,setReason]=useState('');const [assumptions,setAssumptions]=useState('');const [owner,setOwner]=useState('');const [nextStep,setNextStep]=useState('');const [checks,setChecks]=useState({cost:false,scope:false,deadline:false});const [busy,setBusy]=useState(false);const [error,setError]=useState<unknown>(null);
  const offer=data.offers.find(o=>o.id===offerId);const result=data.analysis?.offers?.find(o=>o.id===offerId);const currency=String(data.requirements.currency||'PLN');const unresolved=!data.analysis?.complete||data.pendingAnalysis;const unchecked=data.facts.filter(f=>f.critical!==false&&!data.offers.some(o=>o.excluded_reason&&o.id===(f.offer_id||f.offerId))&&f.confirmation!=='confirmed').length;
  const exportBase=publicDemo?'/api/demo':`/api/cases/${data.id}`;
  return <div className="stack-lg"><SectionHeading eyebrow={t('ŚWIADOMY WYBÓR, ZAPISANA WERSJA','AN INFORMED CHOICE, A SAVED VERSION')} title={t('Twoja decyzja','Your decision')}>{t('Zatwierdzenie nie składa zamówienia. Raport jest migawką dokładnej wersji danych.','Approval does not place an order. The report is a snapshot of the exact data version.')}</SectionHeading>
    {data.decisions.length?<div className="stack">{[...data.decisions].reverse().map(decision=><article className="card saved-decision" key={decision.id}><div className="inline wrap spread"><h3><FileCheck2 size={21}/> {data.offers.find(o=>o.id===(decision.offerId||decision.offer_id))?.name||decision.offerId||decision.offer_id}</h3><Badge tone={decision.current===false?'warn':decision.kind==='conditional'?'warn':'good'}>{decision.current===false?t('Historyczna, wymaga przeglądu','Historical, needs review'):statusLabel(decision.kind,t)}</Badge></div><p>{decision.reason}</p>{decision.assumptions?<p><b>{t('Założenia','Assumptions')}:</b> {decision.assumptions}</p>:null}{decision.nextStep?<p><b>{t('Kolejny krok','Next step')}:</b> {decision.nextStep}</p>:null}<p className="small muted">{t('Wersja','Version')} {decision.revision||valueText(decision.inputRevision)} · {t('Autor','Author')}: {personName(data.members,decision.author||decision.authorId||decision.owner,t)}</p>{decision.reviewReason?<p className="small exclusion">{String(decision.reviewReason)}</p>:null}</article>)}</div>:null}
    {unresolved?<div className="notice warning"><AlertTriangle size={22}/><div><strong>{t('Pełne rozstrzygnięcie nie jest jeszcze możliwe','A fully resolved decision is not yet available')}</strong><p>{t('Pozostają niewiadome, braki albo oczekująca analiza. Możesz zapisać wybór warunkowy z jawnym założeniem, odpowiedzialnością i kolejnym krokiem.','There are unknowns, gaps or pending analysis. You may save a conditional choice with an explicit assumption, owner and next step.')}</p></div></div>:null}
    {!readOnly&&data.role==='owner'&&offer?<form className="card decision-form stack" onSubmit={async e=>{e.preventDefault();setBusy(true);setError(null);try{await mutate('/decisions',{offerId,kind,reason,assumptions:assumptions||undefined,nextStep:nextStep||undefined,owner:owner||undefined,confirmCost:checks.cost,confirmScope:checks.scope,confirmDeadline:checks.deadline});setChecks({cost:false,scope:false,deadline:false});setReason('');}catch(err){setError(err);}finally{setBusy(false);}}}>
      <div className="form-grid"><label className="field"><span>{t('Wybrana oferta','Selected offer')}</span><select value={offerId} onChange={e=>{setOfferId(e.target.value);setChecks({cost:false,scope:false,deadline:false});}}>{data.offers.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label className="field"><span>{t('Rodzaj zapisu','Decision type')}</span><select value={kind} onChange={e=>setKind(e.target.value as 'final'|'conditional')}><option value="final">{t('Decyzja końcowa','Final decision')}</option><option value="conditional">{t('Własny wybór warunkowy','My conditional choice')}</option></select></label></div>
      <div className="decision-summary"><div><span>{t('Pełny koszt','Full cost')}</span><strong>{money(result?.min_cost_minor,currency,lang)}{result?.min_cost_minor!==result?.max_cost_minor?` – ${money(result?.max_cost_minor,currency,lang)}`:''}</strong></div><div><span>{t('Zakres','Scope')}</span><strong>{String(data.requirements.scope||data.requirements.description||t('Według wymagań sprawy','As specified in the case'))}</strong></div><div><span>{t('Gotowość','Ready by')}</span><strong>{displayTime(offer.ready_at,String(data.requirements.timezone||'Europe/Warsaw'))}</strong></div></div>
      <label className="field"><span>{t('Uzasadnienie wyboru','Reason for the choice')}</span><textarea value={reason} onChange={e=>setReason(e.target.value)} required placeholder={t('Jeśli wybierasz droższą ofertę, wyjaśnij preferencję jakościową.','If choosing a more expensive offer, explain your quality preference.')}/></label>{result&&!result.common_winner?<p className="small muted">{t('Ta oferta nie jest wspólnym najtańszym wyborem we wszystkich scenariuszach. Uzasadnienie nie zmienia rachunku.','This offer is not the common lowest-cost choice across all scenarios. Your rationale does not change the calculation.')}</p>:null}
      {kind==='conditional'?<><label className="field"><span>{t('Jawne nierozstrzygnięte założenie','Explicit unresolved assumption')}</span><textarea value={assumptions} onChange={e=>setAssumptions(e.target.value)} required/></label><div className="form-grid"><label className="field"><span>{t('Osoba odpowiedzialna za założenie','Assumption owner')}</span><input value={owner} onChange={e=>setOwner(e.target.value)} required/></label><label className="field"><span>{t('Kolejny krok do wyjaśnienia','Next clarification step')}</span><input value={nextStep} onChange={e=>setNextStep(e.target.value)} required/></label></div></>:null}
      {unchecked||!data.requirements.confirmed?<div className="notice"><p>{unchecked} {t('krytycznych pól wymaga potwierdzenia. Sprawdź również zatwierdzenie wymagań.','critical fields need confirmation. Check that requirements are approved too.')}</p><Button type="button" variant="secondary" onClick={onReview}>{t('Przejdź do przeglądu','Go to review')}<ArrowRight size={16}/></Button></div>:null}
      <Checkbox checked={checks.cost} onChange={cost=>setChecks(prev=>({...prev,cost}))}>{t('Sprawdziłem pełny koszt, składniki oraz założenia cenowe.','I have reviewed the full cost, cost items and pricing assumptions.')}</Checkbox><Checkbox checked={checks.scope} onChange={scope=>setChecks(prev=>({...prev,scope}))}>{t('Sprawdziłem pełny zakres i wszystkie nierozstrzygnięte warunki.','I have reviewed the full scope and all unresolved conditions.')}</Checkbox><Checkbox checked={checks.deadline} onChange={deadline=>setChecks(prev=>({...prev,deadline}))}>{t('Sprawdziłem datę, strefę, termin gotowości i czas obsługi.','I have reviewed the date, time zone, readiness deadline and service duration.')}</Checkbox>{error?<ErrorBox error={error}/>:null}<Button type="submit" busy={busy} disabled={!reason.trim()||!checks.cost||!checks.scope||!checks.deadline||(kind==='final'&&Boolean(unresolved||unchecked||!data.requirements.confirmed||!result?.always_feasible))}><Check size={18}/>{kind==='final'?t('Zatwierdź decyzję dla tej wersji','Approve decision for this version'):t('Zapisz wybór warunkowy','Save conditional choice')}</Button>
    </form>:<div className="notice"><p>{publicDemo?t('Przykład jest tylko do odczytu. Zapisywanie decyzji jest dostępne w pełnej aplikacji po zalogowaniu.','This example is read-only. Saving decisions is available in the full signed-in application.'):data.role!=='owner'?t('Końcową decyzję zatwierdza właściciel sprawy.','The case owner approves the final decision.'):t('Dodaj i przeanalizuj oferty przed decyzją.','Add and analyze offers before making a decision.')}</p></div>}
    <section className="card export-card"><Download size={28}/><div><h3>{t('Pobierz raport z tej wersji','Download this version’s report')}</h3><p>{t('Wymagania, źródła, rachunki, scenariusze, odpowiedzi i autor decyzji. Roboczy lub historyczny stan pozostaje oznaczony.','Requirements, sources, calculations, scenarios, replies and decision author. Draft or historical status stays explicit.')}</p><p className="small muted">{t('Pobrany raport nie aktualizuje się po kolejnych zmianach.','A downloaded report does not update after further changes.')}</p></div><div className="inline wrap"><a className="button button-primary" href={demoOnly?'/demo-report.pdf':`${exportBase}/exports/pdf`} download><Download size={16}/>PDF</a><a className="button button-secondary" href={demoOnly?'/demo-report.json':`${exportBase}/exports/json`} download><Download size={16}/>JSON</a></div></section>
  </div>;
}
export function HistoryPanel({data,mutate,readOnly,publicDemo}: {data:CaseDetail;mutate:MutateCase;readOnly:boolean;publicDemo:boolean}) {
  const {t}=useLang();const [target,setTarget]=useState<number|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState<unknown>(null);const base=publicDemo?'/api/demo':`/api/cases/${data.id}`;
  return <div className="stack-lg"><SectionHeading eyebrow={t('ŚLAD DECYZJI','DECISION TRAIL')} title={t('Historia i wpływ zmian','History and impact of changes')}>{t('Cofnięcie tworzy nową wersję. Wcześniejsze decyzje i eksporty pozostają historią.','Undo creates a new version. Earlier decisions and exports remain historical.')}</SectionHeading>{data.impact?.length?<Impact data={data}/>:null}<ol className="timeline">{data.history?.map((event,i)=><li key={event.id||event.revision||i}><span className="timeline-point"><History size={16}/></span><article className="card"><div className="inline wrap spread"><h3>{event.summary||statusLabel(event.action||event.type||'case_changed',t)}</h3><Badge tone={event.revision===data.revision?'blue':'neutral'}>{t('Wersja','Version')} {event.revision}</Badge></div><p className="small muted">{event.createdAt?new Date(event.createdAt).toLocaleString():''} · {personName(data.members,event.author,t)}</p><div className="inline wrap"><a className="text-link" href={`${base}/exports/json?revision=${event.revision}`} download><Download size={15}/>{t('Dane tej wersji','Data from this version')}</a><a className="text-link" href={`${base}/exports/pdf?revision=${event.revision}`} download>PDF</a>{!readOnly&&event.revision&&event.revision!==data.revision?<button className="text-link" onClick={()=>setTarget(event.revision!)}><RotateCcw size={15}/>{t('Przywróć jako nową wersję','Restore as a new version')}</button>:null}</div></article></li>)}</ol>{!data.history?.length?<Empty title={t('Historia pojawi się po pierwszym zapisie','History appears after the first save')}/>:null}
    <Modal open={target!==null} onOpenChange={open=>!open&&setTarget(null)} title={t('Przywróć wcześniejsze ustalenia','Restore earlier findings')}><p>{t('Przywrócenie wersji','Restoring version')} {target} {t('utworzy nową rewizję i skieruje decyzję do ponownego sprawdzenia. Usuniętego oryginału nie można odtworzyć przez cofnięcie.','will create a new revision and require decision review. Undo cannot restore a deleted original.')}</p>{error?<ErrorBox error={error}/>:null}<Button busy={busy} onClick={async()=>{setBusy(true);setError(null);try{await mutate('/undo',{targetRevision:target});setTarget(null);}catch(e){setError(e);}finally{setBusy(false);}}}><RotateCcw size={17}/>{t('Przywróć jako nową wersję','Restore as a new version')}</Button></Modal>
  </div>;
}
export function MembersPanel({data,mutate,readOnly}: {data:CaseDetail;mutate:MutateCase;readOnly:boolean}) {
  const {t}=useLang();const [role,setRole]=useState('observer');const [invitation,setInvitation]=useState<{url:string;expiresAt:string|number}|null>(null);const [error,setError]=useState<unknown>(null);const [busy,setBusy]=useState(false);const [remove,setRemove]=useState<string|null>(null);const [deleteOpen,setDeleteOpen]=useState(false);const [name,setName]=useState('');const owner=data.role==='owner'&&!readOnly;
  const perform=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError(null);try{await fn();}catch(e){setError(e);}finally{setBusy(false);}};
  return <div className="stack-lg"><SectionHeading eyebrow={t('PRYWATNA SPRAWA','PRIVATE CASE')} title={t('Osoby i dostęp','People and access')}>{t('Tylko uprawnione osoby mogą otworzyć dokumenty. Właściciel zatwierdza końcowy wybór.','Only authorized people can open documents. The owner approves the final choice.')}</SectionHeading><div className="card members-list">{data.members.map((member,i)=><div key={member.userId||member.id||i}><span className="avatar"><Users size={18}/></span><span><strong>{member.name||member.email||member.userId}</strong><small>{member.email}</small></span><Badge>{statusLabel(member.role,t)}</Badge>{owner&&member.role!=='owner'?<Button variant="ghost" onClick={()=>setRemove(member.userId||member.id||'')}><Trash2 size={16}/>{t('Usuń dostęp','Remove access')}</Button>:null}</div>)}</div>{owner?<section className="card stack"><h3>{t('Utwórz jednorazowe zaproszenie','Create a one-time invitation')}</h3><p>{t('Link udostępniasz samodzielnie. Zaproszenie wygasa i może zostać wykorzystane tylko raz po zalogowaniu.','You share the link yourself. The invitation expires and can only be redeemed once after signing in.')}</p><label className="field"><span>{t('Uprawnienia zaproszonej osoby','Invitee permissions')}</span><select value={role} onChange={e=>setRole(e.target.value)}><option value="observer">{t('Obserwator: tylko odczyt','Observer: read only')}</option><option value="editor">{t('Redaktor: dokumenty i ustalenia','Editor: documents and findings')}</option></select></label><Button busy={busy} onClick={()=>perform(async()=>{const result=await mutate('/invitations',{role}) as {url:string;expiresAt:string|number};setInvitation(result);})}><Share2 size={16}/>{t('Utwórz link zaproszenia','Create invitation link')}</Button>{invitation?<div className="notice"><label className="field"><span>{t('Link do samodzielnego udostępnienia','Link to share yourself')}</span><input readOnly value={invitation.url}/></label><CopyButton text={invitation.url}/><p className="small">{t('Wygasa','Expires')}: {new Date(typeof invitation.expiresAt==='number'?invitation.expiresAt*1000:invitation.expiresAt).toLocaleString()}</p></div>:null}</section>:null}
    {error?<ErrorBox error={error}/>:null}{owner?<section className="card danger-zone"><div><h3>{t('Usuń sprawę','Delete case')}</h3><p>{t('Usunięcie obejmuje źródła, cytaty, OCR, cache, raporty i dane pochodne. Pobrane przez użytkowników kopie pozostają poza aplikacją.','Deletion includes sources, quotations, OCR, cache, reports and derived data. Copies downloaded by users remain outside the app.')}</p></div><Button variant="danger" onClick={()=>setDeleteOpen(true)}><Trash2 size={17}/>{t('Usuń sprawę','Delete case')}</Button></section>:null}
    <Modal open={Boolean(remove)} onOpenChange={open=>!open&&setRemove(null)} title={t('Usuń dostęp tej osoby','Remove this person’s access')}><p>{t('Osoba utraci dostęp do tej sprawy, dokumentów i eksportów.','This person will lose access to this case, its documents and exports.')}</p><Button variant="danger" busy={busy} onClick={()=>perform(async()=>{await mutate(`/members/${remove}`,{},'DELETE');setRemove(null);})}>{t('Usuń dostęp','Remove access')}</Button></Modal>
    <Modal open={deleteOpen} onOpenChange={setDeleteOpen} title={t('Trwale usuń tę sprawę','Permanently delete this case')}><p>{t('Wpisz nazwę sprawy, aby potwierdzić usunięcie.','Type the case name to confirm deletion.')}</p><strong>{data.title}</strong><label className="field"><span>{t('Nazwa sprawy do potwierdzenia','Case name for confirmation')}</span><input value={name} onChange={e=>setName(e.target.value)}/></label>{error?<ErrorBox error={error}/>:null}<Button variant="danger" busy={busy} disabled={name!==data.title} onClick={()=>perform(async()=>{await mutate('',{},'DELETE');navigate('/cases');})}><Trash2 size={17}/>{t('Trwale usuń dane','Permanently delete data')}</Button></Modal>
  </div>;
}
